'use client'

import { useState, useRef, useEffect } from 'react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { ArrowRight, Loader2, Sparkles, Check } from 'lucide-react'
import { motion, AnimatePresence } from 'framer-motion'
import { BorderBeam } from '@/components/magicui/border-beam'
import confetti from 'canvas-confetti'

interface InteractivePromptBoxProps {
  onSubmit?: (prompt: string) => void
}

export function InteractivePromptBox({ onSubmit }: InteractivePromptBoxProps) {
  const [prompt, setPrompt] = useState('')
  const [isGenerating, setIsGenerating] = useState(false)
  const [isSuccess, setIsSuccess] = useState(false)
  const [showPreview, setShowPreview] = useState(false)
  const [generatedCode, setGeneratedCode] = useState('')
  const inputRef = useRef<HTMLInputElement>(null)

  // Focus input on mount
  useEffect(() => {
    inputRef.current?.focus()
  }, [])

  const handleSubmit = async () => {
    if (!prompt.trim() || isGenerating) return

    setIsGenerating(true)
    setIsSuccess(false)
    setShowPreview(false)

    // Simulate API call (in real app, this would call your backend)
    setTimeout(() => {
      // Mock response
      const mockCode = `// Generated by Frankenstein.AI
import React from 'react'

export function TodoApp() {
  const [todos, setTodos] = React.useState([])

  return (
    <div className="max-w-2xl mx-auto p-8">
      <h1 className="text-3xl font-bold mb-6">
        ✅ Todo App
      </h1>
      {/* Your AI-generated code continues... */}
    </div>
  )
}`

      setGeneratedCode(mockCode)
      setIsGenerating(false)
      setIsSuccess(true)
      setShowPreview(true)

      // Fire confetti
      confetti({
        particleCount: 100,
        spread: 70,
        origin: { y: 0.6 }
      })

      // Call parent callback
      onSubmit?.(prompt)
    }, 2000)
  }

  const handleKeyPress = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault()
      handleSubmit()
    }
  }

  return (
    <div className="relative max-w-3xl mx-auto">
      {/* Prompt Input Box */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5 }}
        className="relative"
      >
        {/* Glow effect */}
        <div className="absolute -inset-1 bg-gradient-to-r from-horror-purple-600 via-horror-pink-600 to-horror-red-600 rounded-2xl blur-xl opacity-50 group-hover:opacity-75 transition duration-500" />

        <div className="relative glass rounded-2xl p-1">
          <BorderBeam
            size={250}
            duration={12}
            delay={9}
            colorFrom="#a855f7"
            colorTo="#ec4899"
          />

          <div className="relative bg-black/50 backdrop-blur-xl rounded-xl p-2">
            <div className="flex gap-2">
              <Input
                ref={inputRef}
                type="text"
                value={prompt}
                onChange={(e) => setPrompt(e.target.value)}
                onKeyPress={handleKeyPress}
                placeholder="Build me a todo app with authentication..."
                disabled={isGenerating}
                className="flex-1 px-6 py-4 bg-transparent text-white placeholder-gray-500 border-none focus-visible:ring-0 focus-visible:ring-offset-0 text-lg"
              />

              <Button
                size="lg"
                disabled={!prompt.trim() || isGenerating}
                onClick={handleSubmit}
                className="group relative px-8 py-4 bg-gradient-to-r from-horror-purple-600 to-horror-pink-600 hover:from-horror-purple-700 hover:to-horror-pink-700 text-white font-semibold transition-all duration-300 hover:scale-105 disabled:opacity-50 disabled:cursor-not-allowed overflow-hidden"
              >
                {/* Button glow effect */}
                <div className="absolute inset-0 bg-white/20 transform scale-x-0 group-hover:scale-x-100 transition-transform origin-left duration-300" />

                <span className="relative flex items-center gap-2">
                  {isGenerating ? (
                    <>
                      <Loader2 className="w-5 h-5 animate-spin" />
                      Generating
                    </>
                  ) : isSuccess ? (
                    <>
                      <Check className="w-5 h-5" />
                      Done
                    </>
                  ) : (
                    <>
                      Generate
                      <ArrowRight className="w-5 h-5 group-hover:translate-x-1 transition-transform" />
                    </>
                  )}
                </span>
              </Button>
            </div>

            {/* Character count */}
            {prompt.length > 0 && (
              <motion.div
                initial={{ opacity: 0, height: 0 }}
                animate={{ opacity: 1, height: 'auto' }}
                className="px-6 py-2 text-xs text-gray-500"
              >
                {prompt.length} characters
              </motion.div>
            )}
          </div>
        </div>
      </motion.div>

      {/* Code Preview */}
      <AnimatePresence>
        {showPreview && (
          <motion.div
            initial={{ opacity: 0, y: 20, scale: 0.95 }}
            animate={{ opacity: 1, y: 0, scale: 1 }}
            exit={{ opacity: 0, y: -20, scale: 0.95 }}
            transition={{ duration: 0.3 }}
            className="mt-6"
          >
            <div className="glass rounded-xl p-6 border border-horror-purple-500/20">
              {/* Header */}
              <div className="flex items-center justify-between mb-4">
                <div className="flex items-center gap-2">
                  <Sparkles className="w-5 h-5 text-horror-purple-400" />
                  <span className="font-semibold text-white">Generated Code Preview</span>
                </div>
                <Button
                  size="sm"
                  variant="outline"
                  onClick={() => window.location.href = '/studio'}
                  className="border-horror-purple-500/50 hover:bg-horror-purple-500/10"
                >
                  Open in Studio →
                </Button>
              </div>

              {/* Code */}
              <pre className="bg-black/50 rounded-lg p-4 overflow-x-auto">
                <code className="text-sm text-gray-300 font-mono">
                  {generatedCode}
                </code>
              </pre>

              {/* Stats */}
              <div className="mt-4 flex items-center gap-6 text-sm text-gray-400">
                <div className="flex items-center gap-2">
                  <div className="w-2 h-2 rounded-full bg-green-500" />
                  <span>React Component</span>
                </div>
                <div className="flex items-center gap-2">
                  <div className="w-2 h-2 rounded-full bg-blue-500" />
                  <span>TypeScript</span>
                </div>
                <div className="flex items-center gap-2">
                  <div className="w-2 h-2 rounded-full bg-purple-500" />
                  <span>Tailwind CSS</span>
                </div>
              </div>
            </div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Example Prompts */}
      {!showPreview && (
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.5 }}
          className="mt-4 text-center"
        >
          <p className="text-sm text-gray-500 mb-2">Try these examples:</p>
          <div className="flex flex-wrap justify-center gap-2">
            {[
              'Build a todo app',
              'Create a login form',
              'Dashboard with charts',
              'E-commerce product page'
            ].map((example) => (
              <button
                key={example}
                onClick={() => setPrompt(example)}
                className="px-3 py-1 text-xs rounded-full bg-white/5 border border-white/10 text-gray-400 hover:bg-white/10 hover:text-white transition-colors"
              >
                {example}
              </button>
            ))}
          </div>
        </motion.div>
      )}
    </div>
  )
}
